server:
  port: 8081
  servlet:
    context-path: /v1/api

spring:
  application:
    name: signin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.100.213.205:3306/signin?useUnicode=true&characterEncoding=utf-8&serverTimezone=CTT&useSSL=false
    username: root
    password: Mydb6.
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  data:
    mongodb:
      uri: mongodb://engow:rz19940314cr@itrip.wuhansoftware.com:27017/signin
logging:
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
  level:
    com:
      signin:
        dao: DEBUG
mybatis:
  configuration:
    map-underscore-to-camel-case: true

